### ISSUE TITLE
add screenshot to readme

### ISSUE THREAD

**Issue by ninrod** [meh/cancer#5]
why not?

**Comment by meh** [comment]
And what would that show? It's just a window rendering text, it would look the same as any other terminal showing the same shell with the same theme and font.

**Comment by ninrod** [comment]
I don't know. My stuff on iTerm2 looks cool while in mintty things looks shitty. There's a difference. mac rendering? retina? trucolor support?

**Comment by meh** [comment]
The font used and the font rendering definitely make a difference.

But cancer uses Pango, so it will use the platform's font rendering.

**Comment by ninrod** [comment]
ok.
