### ISSUE TITLE
Add sixel support

### ISSUE THREAD

**Issue by meh** [meh/cancer#7]
I want this, everybody wants this, thanks.

Honestly I think this is gonna fuck everything up as far as the renderer is concerned, but alas.

**Comment by FreeFull** [comment]
I've never actually managed to get sixels working in any other terminals. Some terminals, like https://www.enlightenment.org/about-terminology have their own escape sequences for embedding images.

**Comment by meh** [comment]
![It just sneks.](https://cloud.githubusercontent.com/assets/40204/21284906/b961067c-c429-11e6-8425-feb46b62f034.png)
